HomeworkApp/ViewModels/UserViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace HomeworkApp.ViewModels
{
    public class UserViewModel
    {
        [Key, Required]
        public string UserID { get; set; }
        [Required, DisplayName("First Name")]
        public string FirstName { get; set; }
        [Required, DisplayName("Last Name")]
        public string LastName { get; set; }
        [Required, DisplayName("Email")]
        public string EmailAddress { get; set; }
        public Nullable<System.DateTime> JoinedDate { get; set; }
    }
}

HomeworkApp/Controllers/Api/UserController.cs
using HomeworkApp.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Web.Http;

namespace HomeworkApp.Controllers.Api
{
    /// <summary>
    /// Web API Controller for table User.
    /// CRUD operations.
    /// </summary>
    public class UserController : ApiController
    {
        /// <summary>
        /// Get all users.
        /// </summary>
        /// <returns>Return all users</returns>
        public IHttpActionResult Get()
        {
            using (var ctx = new HomeworkEntities())
            {
                var users = ctx.Users.Select(s => new UserModel()
                {
                    UserID = s.UserID,
                    FirstName = s.FirstName,
                    LastName = s.LastName,
                    EmailAddress = s.EmailAddress,
                    JoinedDate = s.JoinedDate
                }).ToList<UserModel>();

                if (users.Count == 0)
                {
                    return NotFound();
                }

                return Ok(users);
            }
        }

        /// <summary>
        /// Get the user by given userID
        /// </summary>
        /// <param name="userID">String for a given userID</param>
        /// <returns>Return the user if found otherwise return bad request</returns>
        public IHttpActionResult GetUserByID(string userID)
        {
            if (userID.Length == 0)
                return BadRequest("Not a valid user id");

            using (var ctx = new HomeworkEntities())
            {
                var existingUser = ctx.Users.Where(s => s.UserID == userID).FirstOrDefault();

                if (existingUser != null)
                {
                    var user = new UserModel()
                    {
                        UserID = existingUser.UserID,
                        FirstName = existingUser.FirstName,
                        LastName = existingUser.LastName,
                        EmailAddress = existingUser.EmailAddress,
                        JoinedDate = existingUser.JoinedDate
                    };
                    return Ok(user);
                }
                else
                {
                    return NotFound();
                }
            }
        }

        /// <summary>
        /// Create a new user
        /// </summary>
        /// <param name="user">UserModel for a user</param>
        /// <returns>Return ok if inserting the user otherwise return bad request</returns>
        public IHttpActionResult Post(UserModel user)
        {
            if (!ModelState.IsValid)
                return BadRequest("Invalid data.");

            using (var ctx = new HomeworkEntities())
            {
                var existingUser = ctx.Users.Where(s => s.UserID == user.UserID).FirstOrDefault<User>();
                if (existingUser != null)
                {
                    return BadRequest("This User ID has been used.");
                }

                ctx.Users.Add(new User()
                {
                    UserID = user.UserID,
                    FirstName = user.FirstName,
                    LastName = user.LastName,
                    EmailAddress = user.EmailAddress,
                    JoinedDate = user.JoinedDate
                });

                ctx.SaveChanges();
            }

            return Ok();
        }

        // <summary>
        /// Update a user
        /// </summary>
        /// <param name="user">UserModel for a user</param>
        /// <returns>Return ok if updating the user otherwise return bad request</returns>
        public IHttpActionResult Put(UserModel user)
        {
            if (!ModelState.IsValid)
                return BadRequest("Invalid data.");

            using (var ctx = new HomeworkEntities())
            {
                var existingUser = ctx.Users.Where(s => s.UserID == user.UserID).FirstOrDefault<User>();

                if (existingUser != null)
                {
                    existingUser.UserID = user.UserID;
                    existingUser.FirstName = user.FirstName;
                    existingUser.LastName = user.LastName;
                    existingUser.EmailAddress = user.EmailAddress;
                    existingUser.JoinedDate = user.JoinedDate;

                    ctx.SaveChanges();
                }
                else
                {
                    return NotFound();
                }
            }

            return Ok();
        }

        // <summary>
        /// Delete a user
        /// </summary>
        /// <param name="userID">String for a userID</param>
        /// <returns>Return ok if the user is deleted otherwise return bad request</returns>
        public IHttpActionResult Delete(string userID)
        {
            if (userID.Length == 0)
                return BadRequest("Not a valid user id");

            using (var ctx = new HomeworkEntities())
            {
                var existingUser = ctx.Users.Where(s => s.UserID == userID).FirstOrDefault();

                if (existingUser != null)
                {
                    ctx.Entry(existingUser).State = System.Data.EntityState.Deleted;
                    ctx.SaveChanges();
                    return Ok();
                }
                else
                {
                    return BadRequest("This user doesn't exist");
                }
            }
        }
    }
}

HomeworkApp/Controllers/UserController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Web;
using System.Web.Mvc;
using HomeworkApp.Models;
using HomeworkApp.ViewModels;

namespace HomeworkApp.Controllers
{
    public class UserController : Controller
    {
        public ActionResult Index(string sort, string search)
        {
            IEnumerable<UserListViewModel> users = null;

            using (var client = new HttpClient())
            {
                client.BaseAddress = new Uri("http://localhost:56441/api/");
                //HTTP GET
                var responseTask = client.GetAsync("user");
                responseTask.Wait();

                var result = responseTask.Result;
                if (result.IsSuccessStatusCode)
                {
                    var readTask = result.Content.ReadAsAsync<IList<UserModel>>();
                    readTask.Wait();

                    users = readTask.Result.Select(userModel => new UserListViewModel
                    {
                        UserID = userModel.UserID,
                        Name = userModel.FirstName + " " + userModel.LastName,
                        EmailAddress = userModel.EmailAddress,
                        JoinedDate = userModel.JoinedDate
                    });
                }
                else //web api sent error response 
                {
                    users = Enumerable.Empty<UserListViewModel>();

                    ModelState.AddModelError(string.Empty, "Server error. Please contact administrator.");
                }
            }
            users = AddFilterAndSorter(users, sort, search);
            return View(users);
        }

        [HttpGet]
        public ActionResult Create()
        {
            return PartialView();
        }

        [HttpPost]
        public ActionResult Create(UserViewModel user, string button)
        {
            if (string.Compare(button, "Cancel", StringComparison.OrdinalIgnoreCase) == 0)
            {
                return RedirectToAction("Index");
            }

            if (!ModelState.IsValid)
            {
                return PartialView();
            }

            using (var client = new HttpClient())
            {
                //add date
                user.JoinedDate = DateTime.Now;

                client.BaseAddress = new Uri("http://localhost:56441/api/user");

                //HTTP POST
                var postTask = client.PostAsJsonAsync<UserModel>("user", ConvertToUserModel(user));
                postTask.Wait();

                var result = postTask.Result;
                if (result.IsSuccessStatusCode)
                {
                    return RedirectToAction("Index");
                }
            }
            ModelState.AddModelError(string.Empty, "Server Error. Please contact administrator.");

            return PartialView(user);
        }

        [HttpGet]
        public ActionResult Edit(string userID)
        {
            return PartialView(GetUserByID(userID));
        }

        [HttpPost]
        public ActionResult Edit(UserViewModel user, string button)
        {
            if (string.Compare(button, "Cancel", StringComparison.OrdinalIgnoreCase) == 0)
            {
                return RedirectToAction("Index");
            }

            if (!UserExists(user.UserID))
            {
                ModelState.AddModelError(string.Empty, "This UserID doesn't exist.");
            }
            else
            {
                using (var client = new HttpClient())
                {
                    client.BaseAddress = new Uri("http://localhost:56441/api/user");

                    //HTTP POST
                    var postTask = client.PutAsJsonAsync<UserModel>("user", ConvertToUserModel(user));
                    postTask.Wait();

                    var result = postTask.Result;
                    if (result.IsSuccessStatusCode)
                    {
                        return RedirectToAction("Index");
                    }
                }
                ModelState.AddModelError(string.Empty, "Server Error. Please contact administrator.");
            }

            return PartialView(user);
        }

        [HttpGet]
        public bool UserExists(string userID)
        {
            return GetUserByID(userID) != null;
        }

        [HttpGet]
        public ActionResult Delete(string userID)
        {
            var user = new UserViewModel() { UserID = userID };
            return PartialView(user);
        }

        [HttpPost]
        public ActionResult Delete(string userID, string button)
        {
            if (string.Compare(button, "Cancel", StringComparison.OrdinalIgnoreCase) == 0)
            {
                return RedirectToAction("Index");
            }

            if (!UserExists(userID))
            {
                ModelState.AddModelError(string.Empty, "This UserID doesn't exist.");
            }
            else
            {
                using (var client = new HttpClient())
                {
                    client.BaseAddress = new Uri("http://localhost:56441/api/user");

                    //HTTP DELETE
                    var postTask = client.DeleteAsync("?userid=" + userID);
                    postTask.Wait();

                    var result = postTask.Result;
                    if (result.IsSuccessStatusCode)
                    {
                        return RedirectToAction("Index");
                    }
                }
                ModelState.AddModelError(string.Empty, "Server Error. Please contact administrator.");
            }

            return View();
        }

        private UserViewModel ConvertToUserViewModel(UserModel userModel)
        {
            return new UserViewModel()
            {
                UserID = userModel.UserID,
                FirstName = userModel.FirstName,
                LastName = userModel.LastName,
                EmailAddress = userModel.EmailAddress,
                JoinedDate = userModel.JoinedDate
            };
        }

        private UserModel ConvertToUserModel(UserViewModel userViewModel)
        {
            return new UserModel()
            {
                UserID = userViewModel.UserID,
                FirstName = userViewModel.FirstName,
                LastName = userViewModel.LastName,
                EmailAddress = userViewModel.EmailAddress,
                JoinedDate = userViewModel.JoinedDate
            };
        }

        private IEnumerable<UserListViewModel> AddFilterAndSorter(IEnumerable<UserListViewModel> users, string sort, string search)
        {
            ViewBag.UserNameSortParameter = string.IsNullOrEmpty(sort) ? "Name_DESC" : string.Empty;
            ViewBag.EmailAddressSortParameter = sort == "EmailAddress" ? "EmailAddress_DESC" : "EmailAddress";
            ViewBag.JoinedDateSortParameter = sort == "JoinedDate" ? "JoinedDate_DESC" : "JoinedDate";

            if (!string.IsNullOrEmpty(search))
            {
                users = users.Where(c => c.Name.ToUpper().StartsWith(search.ToUpper()));
            }

            switch (sort)
            {
                case "Name_DESC":
                    users = users.OrderByDescending(c => c.Name);
                    break;
                case "EmailAddress":
                    users = users.OrderBy(c => c.EmailAddress);
                    break;
                case "EmailAddress_DESC":
                    users = users.OrderByDescending(c => c.EmailAddress);
                    break;
                case "JoinedDate":
                    users = users.OrderBy(c => c.JoinedDate);
                    break;
                case "JoinedDate_DESC":
                    users = users.OrderByDescending(c => c.JoinedDate);
                    break;
                default:
                    users = users.OrderBy(c => c.Name);
                    break;
            }

            return users;
        }

        private UserViewModel GetUserByID(string userID)
        {
            using (var client = new HttpClient())
            {
                client.BaseAddress = new Uri("http://localhost:56441/api/");
                //HTTP GET
                var responseTask = client.GetAsync("user?userID=" + userID);
                responseTask.Wait();

                var result = responseTask.Result;
                if (result.IsSuccessStatusCode)
                {
                    var readTask = result.Content.ReadAsAsync<UserModel>();
                    readTask.Wait();

                    return ConvertToUserViewModel(readTask.Result);
                }
                else //web api sent error response 
                {
                    //log response status here.
                    ModelState.AddModelError(string.Empty, "Not Found.");
                }
            }
            return null;
        }
    }
}

HomeworkApp/Views/User/Create.cshtml
@model HomeworkApp.Models.UserModel

<script type="text/javascript">
    var ButtonKeys = { "EnterKey": 13 };
       $(function () {
           $("#createUser").keypress(function (e) {
               var notSaveButtonHasFocus = (e.target.name == "button" && e.target.value != "Save");
               debugger;
               if (e.which == ButtonKeys.EnterKey && !notSaveButtonHasFocus) {
                   $("#saveUser").click();
                   return false;
               }
           });
       });
</script>

@using (Html.BeginForm("Create", "User", FormMethod.Post, new { id = "createUser" }))
    {
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.UserID, htmlAttributes: new { @class = "control-label control-label-dialog col-md-2 required" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.UserID, new { htmlAttributes = new { @id = "txt-userid", @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.UserID, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.FirstName, htmlAttributes: new { @class = "control-label control-label-dialog col-md-2 required" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FirstName, new { htmlAttributes = new { @id = "txt-fname", @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FirstName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.LastName, htmlAttributes: new { @class = "control-label control-label-dialog col-md-2 required" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.LastName, new { htmlAttributes = new { @id = "txt-lname", @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.LastName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.EmailAddress, htmlAttributes: new { @class = "control-label control-label-dialog col-md-2 required" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.EmailAddress, new { htmlAttributes = new { @id = "txt-email", @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.EmailAddress, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <button value="Cancel" class="btn" name="button">Cancel</button>
                <button value="Reset" class="btn" name="button" onclick="return resetUserFields()">Reset</button>
                <button value="Save" class="btn btn-default" name="button" id="saveUser" onclick="return isValidUser('create')">Save</button>
            </div>
        </div>
    </div>
}

HomeworkApp/Views/User/Delete.cshtml
@model HomeworkApp.ViewModels.UserViewModel

<h3>Do you really want to delete this user : @Html.DisplayFor(model => model.UserID)?</h3>
<br />
<div>
    @using (Html.BeginForm("Delete", "User", new { userId = @Html.DisplayFor(model => model.UserID) }, FormMethod.Post, new { id = "createUser", defaultbutton = "deleteUser" })) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <button value="Cancel" class="btn" name="button">Cancel</button>
            <button value="Delete" class="btn btn-default" name="button" id="deleteUser">Delete</button>
        </div>
    }
</div>

HomeworkApp/Views/User/Edit.cshtml
@model HomeworkApp.ViewModels.UserViewModel

<script type="text/javascript">
    var ButtonKeys = { "EnterKey": 13 };
    $(function () {
        $("#editUser").keypress(function (e) {
            var notSaveButtonHasFocus = (e.target.name == "button" && e.target.value != "Update");
            if (e.which == ButtonKeys.EnterKey && !notSaveButtonHasFocus) {
                $("#updateUser").click();
                return false;
            }
        });
    });
</script>


@using (Html.BeginForm("Edit", "User", FormMethod.Post, new { id = "editUser" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="form-group">
            @Html.LabelFor(model => model.UserID, htmlAttributes: new { @class = "control-label control-label-dialog col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.UserID, new { htmlAttributes = new { @id = "txt-userid", @class = "form-control", @readonly="true" } })
                @Html.ValidationMessageFor(model => model.UserID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.FirstName, htmlAttributes: new { @class = "control-label control-label-dialog col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FirstName, new { htmlAttributes = new { @id = "txt-fname", @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FirstName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.LastName, htmlAttributes: new { @class = "control-label control-label-dialog col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.LastName, new { htmlAttributes = new { @id = "txt-lname", @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.LastName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.EmailAddress, htmlAttributes: new { @class = "control-label control-label-dialog col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.EmailAddress, new { htmlAttributes = new { @id = "txt-email", @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.EmailAddress, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <button value="Cancel" class="btn" name="button">Cancel</button>
                <button value="Reset" class="btn" name="button" onclick="return restoreUserFields()">Restore</button>
                <button value="Update" class="btn btn-default" name="button" id="updateUser" onclick="return isValidUser('update')">Update</button>
            </div>
        </div>
        <div>
            @Html.HiddenFor(model => model.FirstName, htmlAttributes: new { @id = "original-fname" })
            @Html.HiddenFor(model => model.LastName, htmlAttributes: new { @id = "original-lname" })
            @Html.HiddenFor(model => model.EmailAddress, htmlAttributes: new { @id = "original-email" })
            @Html.HiddenFor(model => model.JoinedDate)
        </div>
    </div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

HomeworkApp/Views/User/Index.cshtml
@model IEnumerable<HomeworkApp.ViewModels.UserListViewModel>

@{
    ViewBag.Title = "Homework";
}

<h2 style="text-align: center">User Administration</h2>

@using (Html.BeginRouteForm(null, FormMethod.Get))
{
    <span>
        @Html.TextBox("search")
        <input type="submit" value="Filter" class="btn" style="font-weight:bold" />
    </span>
    <span class="open-dialog">
        @Html.ActionLink("Create User", "Create", "User", null, new { @id = "openDialog" })
    </span>
}
<br />
<table class="table">
    <tr>
        <th style="font-size:large">
            @Html.ActionLink(
            Html.DisplayNameFor(model => model.Name).ToString(),
            "Index",
            new
            {
                search = Request.QueryString["search"],
                sort = ViewBag.UserNameSortParameter
            })
        </th>
        <th style="font-size:large">
            @Html.ActionLink(
            Html.DisplayNameFor(model => model.EmailAddress).ToString(),
            "Index",
            new
            {
                search = Request.QueryString["search"],
                sort = ViewBag.EmailAddressSortParameter
            })
        </th>
        <th style="font-size:large">
            @Html.ActionLink(
            Html.DisplayNameFor(model => model.JoinedDate).ToString(),
            "Index",
            new
            {
                search = Request.QueryString["search"],
                sort = ViewBag.JoinedDateSortParameter
            })
        </th>
        <th>
        </th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            <div>@Html.DisplayFor(modelItem => item.Name)</div>
            <div>@Html.DisplayFor(modelItem => item.UserID)</div>
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.EmailAddress)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.JoinedDate)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", "user", new { userID = item.UserID }, new { @class = "openEditDialog" })
            |
            @Html.ActionLink("Delete", "Delete", new { userID = item.UserID }, new { @class = "openDeleteDialog" })
        </td>
    </tr>
}

</table>

<!-- place holders for CRUD dialog -->
<div id="dialog-create"></div>
<div id="dialog-edit"></div>
<div id="dialog-delete"></div>